apiVersion: v1
kind: Pod
metadata:
  name: ros-remotepc-domain-32
  labels:
    app: ros-remotepc
    ros-domain-id: "32"
spec:
  nodeName: turtlebot-burger-3
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  restartPolicy: Always

  containers:
    - name: ros2-remotepc
      image: ketidevit2/ros2-remotepc-domain-32:0.0.1-arm64
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash", "-c", "tail -f /dev/null"]
      stdin: true
      tty: true

      env:
        - name: ROS_DOMAIN_ID
          value: "32"

        - name: ROS_DISCOVERY_SERVER
          value: "10.0.0.39:11811"

        - name: RMW_IMPLEMENTATION
          value: "rmw_fastrtps_cpp"

        - name: ROS_LOCALHOST_ONLY
          value: "0"

        - name: HOME
          value: "/root"

        - name: ROS_HOME
          value: "/root/.ros"

        - name: RCUTILS_LOGGING_USE_STDOUT
          value: "1"

        - name: RCUTILS_CONSOLE_OUTPUT_FORMAT
          value: "[{severity}] [{name}]: {message}"
apiVersion: v1
kind: Pod
metadata:
  name: ros-remotepc-domain-32
  labels:
    app: ros-remotepc
    ros-domain-id: "32"
spec:
  nodeName: turtlebot-burger-3
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  restartPolicy: Always

  containers:
    - name: ros2-remotepc
      image: ketidevit2/ros2-remotepc-domain-32:0.0.1-arm64
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash", "-c", "tail -f /dev/null"]
      stdin: true
      tty: true

      env:
        - name: ROS_DOMAIN_ID
          value: "32"

        - name: ROS_DISCOVERY_SERVER
          value: "10.0.0.39:11811"

        - name: RMW_IMPLEMENTATION
          value: "rmw_fastrtps_cpp"

        - name: ROS_LOCALHOST_ONLY
          value: "0"

        - name: HOME
          value: "/tmp/ros_home"

        - name: ROS_HOME
          value: "/tmp/.ros"

        - name: RCUTILS_LOGGING_USE_STDOUT
          value: "1"

        - name: RCUTILS_CONSOLE_OUTPUT_FORMAT
          value: "[{severity}] [{name}]: {message}"

      volumeMounts:
        - name: ros-home
          mountPath: /tmp

  volumes:
    - name: ros-home
      emptyDir: {}

